services:
  slior-db:
    container_name: slior-db
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: slior
      POSTGRES_USER: slior
      POSTGRES_PASSWORD: slior
    ports:
      - "5432:5432"
    volumes:
      - slior-db-data:/var/lib/postgresql/data
    networks:
      - slior-net

  slior-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: slior-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - slior-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend-logs:/app/logs
      - ./backend-labels:/app/generated-labels
    networks:
      - slior-net

networks:
  slior-net:
    name: slior-net

volumes:
  slior-db-data:
